import { OnInit, EventEmitter, AfterViewInit, ElementRef } from '@angular/core';
import { MdsDatetimePickerCoreComponent } from './core/mds-datetime-picker-core.component';
import { TextBoxTypeEnum, TemplateTypeEnum } from "../assests/enums";
import { IDate, IRangeDate } from "../assests/interfaces";
export declare class MdsDatetimePickerComponent implements OnInit, AfterViewInit {
    private element;
    constructor(element: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    mdsDateTimePickerCore: MdsDatetimePickerCoreComponent;
    templateType: TemplateTypeEnum;
    textBoxType: TextBoxTypeEnum;
    initialValue: string;
    inLine: boolean;
    persianChar: boolean;
    rangeSelector: boolean;
    isPersian: boolean;
    timePicker: boolean;
    placeHolder: string;
    buttonIcon: string;
    format: string;
    dateChanged: EventEmitter<IDate>;
    rangeDateChanged: EventEmitter<IRangeDate>;
    keyDown: EventEmitter<any>;
    blur: EventEmitter<any>;
    focus: EventEmitter<any>;
    textboxValue: string;
    private topOffset;
    private leftOffset;
    private showDatePicker;
    private afterViewInit;
    private alreadyShowDatePickerClicked;
    private oldDateValue;
    private setDateTime(dateTimeString);
    dateChangedHandler(date: IDate): void;
    rangeDateChangedHandler(rangeDate: IRangeDate): void;
    showDatePickerButtonClicked(): void;
    dateTimeTextBoxOnFocus(event: any): void;
    dateTimeTextBoxOnBlur(event: any): void;
    dateTimeTextBoxOnKeyDown(event: any): void;
}
