import { OnInit, EventEmitter, AfterViewInit, ElementRef } from '@angular/core';
import { TextBoxTypeEnum, TemplateTypeEnum } from "../assests/enums";
import { IDate, IRangeDate } from "../assests/interfaces";
export declare class MdsDatetimePickerComponent implements OnInit, AfterViewInit {
    private element;
    constructor(element: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    private mdsDateTimePickerCore;
    templateType: TemplateTypeEnum;
    textBoxType: TextBoxTypeEnum;
    initialValue: string;
    inLine: boolean;
    persianChar: boolean;
    rangeSelector: boolean;
    isPersian: boolean;
    timePicker: boolean;
    placeHolder: string;
    buttonIcon: string;
    format: string;
    dateChanged: EventEmitter<IDate>;
    rangeDateChanged: EventEmitter<IRangeDate>;
    keyDown: EventEmitter<any>;
    blur: EventEmitter<any>;
    focus: EventEmitter<any>;
    textboxValue: string;
    private topOffset;
    private leftOffset;
    private showDatePicker;
    private afterViewInit;
    private alreadyShowDatePickerClicked;
    private oldDateValue;
    private setDateTime(dateTimeString);
    private dateChangedHandler(date);
    private rangeDateChangedHandler(rangeDate);
    private showDatePickerButtonClicked();
    private dateTimeTextBoxOnFocusHandler(event);
    private dateTimeTextBoxOnBlurHandler(event);
    private dateTimeTextBoxOnKeyDownHandler(event);
    clear(): void;
}
