import { OnInit, EventEmitter } from '@angular/core';
import { MdsDatetimePickerResourcesService } from '../../services/mds-datetime-picker-resources.service';
import { TemplateTypeEnum } from "../../assests/enums";
import { IDate, IRangeDate, IDay } from "../../assests/interfaces";
export declare class MdsDatetimePickerCoreComponent implements OnInit {
    private resourcesService;
    constructor(resourcesService: MdsDatetimePickerResourcesService);
    ngOnInit(): void;
    templateType: TemplateTypeEnum;
    initialValue: string;
    persianChar: boolean;
    isPersian: boolean;
    rangeSelector: boolean;
    timePicker: boolean;
    format: string;
    dateChanged: EventEmitter<IDate>;
    rangeDateChanged: EventEmitter<IRangeDate>;
    daysAnimationStateName: string;
    monthOrYearSelectorVisibilityStateName: string;
    monthSelectorVisibilityStateName: string;
    yearSelectorVisibilityStateName: string;
    private showMonthSelectorBlock;
    private showYearsSelectorBlock;
    private splitStartEndDateString(dateString);
    private setSelectedRangeDateTimes(dateTimes);
    private setSelectedRangePersianDateTimes(persianDateTimes);
    private readonly persianStartDayOfMonth;
    private readonly gregorianStartDayOfMonth;
    setDateTimeByDate(dateTime: Date): void;
    setDateTime(date: IDate): void;
    setDateTimeByString(dateTimeString: string): void;
    clearDateTimePicker(): void;
    private _dateTime;
    private dateTime;
    private _persianDateTime;
    private readonly persianDateTime;
    private _selectedDateTime;
    private selectedDateTime;
    private _selectedPersianDateTime;
    private readonly selectedPersianDateTime;
    private _selectedStartDateTime;
    private selectedStartDateTime;
    private _selectedPersianStartDateTime;
    private readonly selectedPersianStartDateTime;
    private _selectedEndDateTime;
    private selectedEndDateTime;
    private _selectedPersianEndDateTime;
    private readonly selectedPersianEndDateTime;
    private startMdsPersianDateTimeToDateTemp;
    private endMdsPersianDateTimeToDateTemp;
    yearsToSelect: string[];
    daysInMonth: IDay[];
    weekDayNames: string[];
    resources: any;
    readonly getValue: string;
    private readonly year;
    readonly yearString: string;
    private readonly month;
    readonly monthName: string;
    readonly day: number;
    readonly monthNames: string[];
    readonly weekdayNames: string[];
    readonly hour: string;
    readonly minute: string;
    readonly second: string;
    readonly isRejectButtonDisable: boolean;
    readonly isConfirmButtonDisable: boolean;
    private updateYearsList();
    private getDayObject(year, month, day, disabled, holiday, isToday);
    private readonly isRangeSelectorReady;
    readonly getDate: IDate;
    readonly getRangeDates: IRangeDate;
    private updateMonthDays();
    private fireChangeEvent();
    private fireRangeChangeEvent();
    private resetToFalseRangeParametersInMonthDays();
    hideSelecMonthAndYearBlock(): void;
    resetIncompleteRanges(): void;
    monthButtonOnClick(): void;
    selectYearButtonOnClick(): void;
    monthsBlockVisibilityAnimationDone(): void;
    yearsBlockVisibilityAnimationDone(): void;
    nextYearButtonOnClick(): void;
    nextMonthButtonOnClick(): void;
    previousMonthButtonOnClick(): void;
    previousYearButtonOnClick(): void;
    hourUpButtonOnClick(): void;
    hourDownButtonOnClick(): void;
    minuteUpButtonOnClick(): void;
    minuteDownButtonOnClick(): void;
    secondUpButtonOnClick(): void;
    secondDownButtonOnClick(): void;
    monthOnClick(selectedMonthName: any): void;
    yearOnClick(selectedYear: any): void;
    todayButtonOnClick(): void;
    dayButtonOnClick(dayObject: IDay): void;
    dayButtonOnHover(dayObject: IDay): void;
    rejectButtonOnClick(): void;
    confirmButtonOnClick(): void;
}
